oceanbase-ce:
  servers:
  - 127.0.0.1
  global:
    home_path: /opt/oceanbase/ob_data4.3/ob_data8
    devname: lo
    mysql_port: 8881
    rpc_port: 8882
    zone: zone1
    cluster_id: 1
    memory_limit: 50G
    system_memory: 12G
    __min_full_resource_pool_memory: 5368709120
    datafile_size: 30G
    log_disk_size: 30G
    syslog_level: ERROR
    enable_syslog_recycle: true
    max_syslog_file_count: 4
    root_password: 123

