obd cluster reload ob_ins1
obd cluster reload ob_ins2
obd cluster reload ob_ins3
obd cluster reload ob_ins4
obd cluster reload ob_ins5
obd cluster reload ob_ins6
obd cluster reload ob_ins7
obd cluster reload ob_ins8
obd cluster reload ob_ins9
