obd cluster restart ob_ins1
obd cluster restart ob_ins2
obd cluster restart ob_ins3
obd cluster restart ob_ins4
obd cluster restart ob_ins5
obd cluster restart ob_ins6
obd cluster restart ob_ins7
obd cluster restart ob_ins8
obd cluster restart ob_ins9
