obd cluster restart ob_ins4.3_1
obd cluster restart ob_ins4.3_2
obd cluster restart ob_ins4.3_3
obd cluster restart ob_ins4.3_4
obd cluster restart ob_ins4.3_5
obd cluster restart ob_ins4.3_6
obd cluster restart ob_ins4.3_7
obd cluster restart ob_ins4.3_8
obd cluster restart ob_ins4.3_9
