oceanbase-ce:
  servers:
  - 127.0.0.1
  global:
    home_path: /home/zhr/ob_data
    devname: lo
    mysql_port: 3881
    rpc_port: 3882
    zone: zone1
    cluster_id: 1
    memory_limit: 100G
    system_memory: 12G
    __min_full_resource_pool_memory: 5368709120
    datafile_size: 50G
    log_disk_size: 50G
    syslog_level: ERROR
    enable_syslog_recycle: true
    max_syslog_file_count: 4

